name: patches-client

dependencies:
      - base < 5
      - react-flux
      - servant-client
      - crdt-tree-vector
      - ghcjs-base
      - aeson
      - containers
      - servant
      - transformers
      - ghcjs-prim
      - http-client
      - deepseq
      - text
      - string-conversions

ghc-options:
  -Wall

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
      - test/exe
      - ../src
      - src
    dependencies:
      - hspec
      - QuickCheck
      - quickcheck-instances

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - src
      - src/exe
      - ../src
