name: patches-client

dependencies:
      - base < 5
      - react-flux
      - servant-client
      - crdt-tree-vector
      - ghcjs-base
      - aeson
      - containers
      - servant
      - transformers
      - ghcjs-prim

tests:
  spec:
    main: ClientTests.hs
    source-dirs:
      - test
      - ../src
      - src
    dependencies:
      - hspec
      - mockery

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - src
      - src/exe
      - ../src
