name: patches-client

dependencies:
      - base < 5
      - react-flux

tests:
  spec:
    main: ClientTests.hs
    source-dirs:
      - test
      - ../src
    dependencies:
      - hspec
      - mockery

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - src
      - src/exe
      - ../src
    dependencies:
      - crdt-tree-vector
      - aeson
      - containers
      - servant
