name: patches-client

dependencies:
  - base < 5

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - src
    dependencies:
      - react-flux
