name: crdt-chat-client

dependencies:
      - base < 5
      - react-flux
      - servant-client
      - crdt-tree-vector
      - ghcjs-base
      - aeson
      - containers
      - servant
      - transformers
      - ghcjs-prim
      - http-client
      - deepseq
      - text
      - string-conversions
      - uuid >= 1.3.12
      - random
      - operational
      - operational-mocks
      - bytestring

ghc-options: >
  -Wall -Werror
  -fno-warn-name-shadowing

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
      - test/exe
      - ../src
      - src
    dependencies:
      - hspec
      - QuickCheck
      - quickcheck-instances

executables:
  crdt-chat-client:
    main: Main.hs
    source-dirs:
      - src
      - src/exe
      - ../src
