packages:
  - ./.
  - location:
      git: https://github.com/haskell-servant/servant
      commit: 6c5afe8fb3592b1364e2688b61c6007392047fa9
    extra-dep: true
    subdirs:
      - servant
      - servant-client
  - location: /home/shahn/src/crdt-tree-vector
    #  git: https://github.com/soenkehahn/crdt-tree-vector
    #  commit: 7c98fa4
    extra-dep: true

resolver: lts-5.12

compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

extra-deps:
  - react-flux-1.1.0
