name: run-tests

ghc-options: -Wall

dependencies:
  - base < 5

executables:
  noop:
    main: Noop.hs

tests:
  spec:
    main: AllTests.hs
    source-dirs:
      - ./.
      - ../client/test
      - ../client/src
      - ../src
      - ../test
    dependencies:
      - hspec
      - http-client
      - deepseq
      - servant-client
      - transformers
      - quickcheck-instances
      - QuickCheck
      - string-conversions
      - text
      - wai
      - wai-make-assets
      - servant-server
      - warp
      - directory
      - react-flux
      - crdt-tree-vector
      - aeson
      - containers
      - servant
      - uuid >= 1.3.12
      - random
      - operational
      - operational-mocks
      - bytestring
      - http-types
      - mockery
