#!/usr/bin/env bash

set -o errexit

echo testing server and client...
STACK_YAML=stack-run-tests.yaml stack build
STACK_YAML=stack-run-tests.yaml stack test
echo testing server...
stack test
echo testing client...
(cd client; stack test)
echo building client...
(cd client; make)
