name: crdt-chat
version: "0.1"

dependencies:
      - base < 5
      - warp
      - wai
      - wai-make-assets
      - servant
      - crdt-tree-vector
      - containers
      - transformers
      - aeson
      - servant-server
      - text
      - uuid >= 1.3.12
      - string-conversions
      - bytestring
      - http-types
      - network-uri
      - random
      - template-haskell
      - directory

tests:
  spec:
    main: ServerAndClientTests.hs
    source-dirs:
      - test
      - src
      - client/test
      - client/src
    dependencies:
      - hspec
      - http-client
      - servant-client
      - mockery
      - operational
      - operational-mocks
      - react-flux
      - QuickCheck
      - quickcheck-instances
      - deepseq

executables:
  patches-server:
    main: Main.hs
    source-dirs:
      - src/exe
    dependencies:
      - crdt-chat

library:
  source-dirs:
    - src
  exposed-modules:
    - Network.Wai.Application.CrdtChat
