resolver: lts-5.12
packages:
  - '.'
  - location:
      git: https://github.com/haskell-servant/servant
      commit: 6c5afe8fb3592b1364e2688b61c6007392047fa9
    extra-dep: true
    subdirs:
      - servant
      - servant-client
      - servant-server
  - location:
      git: https://github.com/soenkehahn/crdt-tree-vector
      commit: 258712c
    extra-dep: true
  - location:
      git: https://github.com/soenkehahn/wai-make-assets
      commit: 7c43ee0
    extra-dep: true
  - location:
      git: https://github.com/soenkehahn/operational-mocks
      commit: f22dfdd
    extra-dep: true
extra-deps:
  - warp-3.2.6
  - http2-1.6.0
  - react-flux-1.1.1
