resolver: lts-5.12
packages:
  - '.'
  - location:
      git: https://github.com/haskell-servant/servant
      commit: 6c5afe8fb3592b1364e2688b61c6007392047fa9
    extra-dep: true
    subdirs:
      - servant
      - servant-client
      - servant-server
  - location: /home/shahn/src/crdt-tree-vector
      # git: https://github.com/soenkehahn/crdt-tree-vector
      # commit: 7c98fa4
    extra-dep: true
extra-deps:
  - wai-make-assets-0.1.1
  - warp-3.2.6
  - http2-1.6.0
